### ISSUE TITLE
Handle Logout using Login Manager?

### ISSUE THREAD

**Issue by karthickvkumar** [facebook/react-native-fbsdk#128]
Hi,
Thanks for this awesome library, how to handle logout using Login Manager. For Login Button there is an onLogoutFinished function which handles the logout. But in Login Manager how this need to handle.

Thanks in Advance

**Comment by dzhuowen** [comment]
RNSDK is a wrapper around the native sdk, so it only provides the existing functions of the native sdk for now. Unfortunately in native sdk we don't have a handler for log out :-(.

**Comment by ajoshdee** [comment]
is it possible to just log it out without the handler?

**Comment by dzhuowen** [comment]
You can log out without using the logout handler in LoginButton or call logout method in FBSDKManager.

**Comment by Sciandra-Leva** [comment]
I'm writing here since I'm working on the same "issue": apparently, by calling 
`
LoginManager.logOut()
`

It is possible to logout the current facebook session (correct me if I'm wrong).

But this method returns undefined; so I can't use a `.then()` to to something after the logout has been successful. Is it just me or it should at least return a response, something?

**Comment by Madhur2207** [comment]
Use this code on any component to log out -
<LoginButton
onLoginFinished={
() => console.log("log in.")
}
onLogoutFinished={() => console.log("logout.")}/>
