### ISSUE TITLE
Build Failed: Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by ZoharLiran** [facebook/react-native-fbsdk#155]
I hope someone can help with this since I have been recreating this issue a few times on an empty app:
1. Creating an app with `react-native init AppName`
2. `rnpm install react-native-fbsdk`
3. `cd ios/`
4. `pod init`
5. placing the required text in the pod file
6. `pod install`
7. setting up the FB sdk information in the `info.plist`
8. running `react-native run-ios` results in a failed `** BUILD FAILED **`
```
The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/Troop.app/Troop normal x86_64
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/Troop.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```
Any ideas?

**Comment by mcrumm** [comment]
I got the same error.  I was able to get my app to build by removing the `react-native-fbsdkshare` from the Podfile, but obviously that's not ideal.

**Comment by ZoharLiran** [comment]
I'll give that a try @mcrumm , although I do want to share via facebook on this app so removing this will be a problem.

**Comment by chrisp-fb** [comment]
When you modified the Info.plist, did you accidentally delete the `CFBundleIdentifier` entry? You can edit the Info.plist in a text editor to see the raw xml (or in Xcode, right click and Open As -> Source Code). You typically should have an entry like 
```
        <key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>

```

**Comment by ZoharLiran** [comment]
@chrisp-fb I did not delete it, made sure it is there

**Comment by chrisp-fb** [comment]
Can you zip up and upload the project somewhere or share it? I can't reproduce the problem. And I don't think this is an issue specific to react-native-fbsdk but can try to look at any samples you can provide. Also what version of Xcode and react-native are you using?

**Comment by ZoharLiran** [comment]
@chrisp-fb I uploaded the test code with step by step commits to the following repo:
https://github.com/ZoharLiran/fbsdk_login_test
for you to see.

**Comment by chrisp-fb** [comment]
I cloned your repo and was not able to reproduce that error. I did have to do some clean up:
* set up all the react native stuff which was not in the repo: `npm install react-native`, `npm install --save react-native-fbsdk`, `pod install`.
* fix up framework search path to be ~/Documents/FacebookSDK (instead of /Users/zohar/Documents/FacebookSDKs-iOS-20160412) which is where I have the Facebook SDK frameworks installed.
* add the `$(inherited)` flag to the Troop target's build setting's linker flag
* add missing `LSApplicationQueriesSchemes` entry to the Info.plist required by the Facebook SDK (technically this absence would cause the SDK to throw and not be related to what you reported)
* removed redundant linking of the `libRCTFBSDKCore.a` and `FBSDKCoreKit.framework` libs from the Troop target. The only thing Troop should link is `libPods-Troop.a` since pods takes care of the others.

and after that, I could start the app in the simulator, though I did see a "react-packager has encountered an internal error, please check your terminal error output for more details" error but the app did get installed into the simulator correctly (both via `react-native run-ios` or if I open the workspace manually in Xcode).

if you can still repro with that repo from a clean clone, please provide the explicit set of steps (starting with `git clone...`) so that I can try to reproduce. Alternatively, there was an alternate set up guide https://medium.com/call-stack/login-users-with-facebook-in-react-native-4b230b847899#.s6w7i4vy0 that might be helpful to you.

(I'm on the same versions of tools except for Xcode 7.3.1)

**Comment by ZoharLiran** [comment]
Here is my understanding of what I need to do to replicate your changes:
- so according to the `rnpm` instructions running `sudo rnpm install react-native-fbsdk` is equal to running `npm install --save react-native-fbsdk`. 
and as you can see in my `package.json` the package is saved. so first I am curious as to why you are saying that you needed to run `npm install --save react-native-fbsdk`
- Your second step I assume that is not needed for me since I have that in the indicated path
- In your third step where you add the `$(inherited)` flag I am assuming you are doing so in the `Troop.xcworkspace` instead of the `Troop.xcodeproj` as the `Pod` instructions specified right?
- I added the `LSApplicationQueriesSchemes` in the `info.plist`
- Where are you removing the linking to `libRCTFBSDKCore.a` and `FBSDKCoreKit.framework` ? can you please show what to do in order to remove those links? by the way, FYI - the only linking I did was using `rnpm` when I installed the package

Thank you very much for your help

**Comment by chrisp-fb** [comment]
* You're right I didn't need the --save switch since it's in your package.json and I should have just ran `npm install` to set everything up.
* Right now you should not use rnpm since the current instructions use Cocoapods (we'll improve this flow).
* re: `$(inherited)`, yep, per the last part of our README 3.2 instructions. The setting is for the Troop target so it doesn't matter if you open the workspace or the individual xcodeproj - it would change the `Troop.xcodeproj/project.pbxproj` file
* I submitted a PR to your repo https://github.com/ZoharLiran/fbsdk_login_test/pull/1 showing the changes I made.
* I was able to get the app to run successful, the package manager error seemed to be caused by some corruption in my node modules so I blew those away and restarted the react-native module.

If this doesn't help, I'd suggest starting a new project using the steps in https://blog.callstack.io/login-users-with-facebook-in-react-native-4b230b847899#.daz6kl7ce which may be more clear, until we get the improved integration steps in the next release.

**Comment by mcrumm** [comment]
@ZoharLiran `pod update` solved the problem for me.  I needed v4.11 of the FBSDK* pods to get past the error.

**Comment by ZoharLiran** [comment]
@chrisp-fb Thank you very much. Your PR works. I have a few final questions regarding the changes you made:
1. The access token returns as null. any idea about that?
2. the changes you made in `Manifest.lock` and `Podfile.lock` where are they coming from?
3. the changes you made in `project.pbxproj`:
  - path changes - why are those needed? the path was pointing to where the sdk was?
  - `$(inherited)` are clear
  - What are the changes in lines 15, 17, 49, 50 ? 
4. When I actually log on using the app in the simulator after I click `Continue as Zohar` I just get a blank screen with the `Done` link on the top left. if I click `Done` I get the native alert saying 
5. In the console I get the warnings:
`index.ios.bundle:13968Warning: ReactNative.Component is deprecated. Use React.Component from the "react" package instead.`
and the same about `PropTypes` and `createElement`, are those known to the team? or am I doing something wrong?

Thank you!

**Comment by chrisp-fb** [comment]
1. In my PR I didn't actually implement any calls to start a login flow - it only checks to see if there is an active token (e.g., if user is logged in) to make sure there's no other crashes or integration problems, so we can expect my code to return null. You can add a login button (https://github.com/facebook/react-native-fbsdk/#login) to start a login flow.

2. I don't know actually, maybe cocoapods was doing something on my machine.

3. The framework search path change might not actually have been needed in this case now that you mention it since we're using Cocoapods to build everything - I had changed it since that's something I automatically do to point to the location where I installed the FacebookSDKs (e.g., FBSDKCoreKit.framework, etc).

3. The changes in 15,17,49,50, 66, 67, 121 were to remove the redundant linking - this can be done by removing the libraries from the project navigator or removing them from the linking step of the build phases.

4. Did you finish the rest of the set up which requires following the steps in https://developers.facebook.com/docs/ios/getting-started , specifically to update the app delegate: 
```
//  AppDelegate.m
#import <FBSDKCoreKit/FBSDKCoreKit.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application
    didFinishLaunchingWithOptions:launchOptions];
  // Add any custom logic here.
  return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
    openURL:url
    sourceApplication:sourceApplication
    annotation:annotation
  ];
  // Add any custom logic here.
  return handled;
}
```

5. not sure off hand, sounds like react native core is deprecating some of the APIs

Glad we got it working, and happy hacking!

**Comment by leinov** [comment]
i also have this question i remve the node_modules and install again
