### ISSUE TITLE
shareApi.canShare() is not a function

### ISSUE THREAD

**Issue by niksinfinite10** [facebook/react-native-fbsdk#196]
We tried exactly the instructions mentioned but we are constantly getting this error 

React Native Version : 0.22.0
Latest version of Facebook SDK
latest version of react-native-fbsdk

**Its really surprising that ShareDialog.canShow() works fine but ShareApi.canShare() dosent work**

![image](https://cloud.githubusercontent.com/assets/13973608/15563310/3edff7be-22bc-11e6-96bf-8576c4e8d01a.png)

**Comment by niksinfinite10** [comment]
This was happening because Login Token didnt had publish_actions permission when we gave that it started working.

**Comment by dzhuowen** [comment]
`ShareAPI.canShare` is only available for [Android](https://github.com/facebook/react-native-fbsdk/blob/master/js/FBShareApi.js#L30-L31). This is fine for now b/c `ShareAPI.canShare` in the [iOS SDK](https://github.com/facebook/facebook-ios-sdk/blob/c570eaef543b231dafb6d89b6d395ae28dac2224/FBSDKShareKit/FBSDKShareKit/FBSDKShareAPI.m#L106-L109) returns `YES` in anyway.  
But you're right this is confusing and should be fixed in next release. Feel free to submit a pull request  for this. Thanks!
