### ISSUE TITLE
podspecs removed?

### ISSUE THREAD

**Issue by emroot** [facebook/react-native-fbsdk#210]
Any reason why the `.podspec` files were removed with version `0.2.0` in this [commit](https://github.com/facebook/react-native-fbsdk/commit/1974362d6af8b4adba75831b3e4fb773671ece71)?

**Comment by bcalik** [comment]
My build fails because of this. Could anybody please explain what to do?

**Comment by dzhuowen** [comment]
See https://github.com/facebook/react-native-fbsdk/issues/184.

**Comment by bcalik** [comment]
So what to do? I get error:
`'FBSDKCoreKit/FBSDKCoreKit.h' file not found`

Installation introduction says `Along with FBSDKCoreKit.framework, don't forget to import FBSDKShareKit.framework and FBSDKLoginKit.framework into your Xcode project.` But where are those files? I can not find them in node_modules.

**Comment by emroot** [comment]
@dzhuowen any wiliness to bring `podspec` back? kinda sucks that now we have to add the sdk, especially when you have multiple developers, you just can't drop the files in xcode, you have to copy them which adds up to the github repo... On top of that, now we end up with a mix of pods and frameworks

**Comment by cmcewen** [comment]
I'd also vote for maintaining the podspec as an option. React Native core maintains a [podspec](https://github.com/facebook/react-native/blob/master/React.podspec) and I think it's worthwhile to adopt since there are other libraries that need to include libraries:
https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/react-native-branch.podspec 
https://github.com/cmcewen/react-native-gcm-ios/blob/master/react-native-gcm-ios.podspec

It's a pain to set up for sure, but I think it's worthwhile once you do it. I just point people to this article: https://blog.callstack.io/login-users-with-facebook-in-react-native-4b230b847899#.1x5p29tmq
