### ISSUE TITLE
Question: Can someone clarify the difference between Share Dialogs and Share API?

### ISSUE THREAD

**Issue by bendellarocco** [facebook/react-native-fbsdk#229]
I am looking into using this for my current project.  I was just wondering if someone could clarify the difference between Share Dialogs and Share API?  I see one needs a permission while the other does not.  What is the reasoning?  What is the difference in capabilities?  The read me does not seem to give any of this information and I would like to ensure I am using the correct one.  Any information would greatly be appreciated.

Thank you

**Comment by chrisp-fb** [comment]
https://developers.facebook.com/docs/sharing/overview can help but here's a quick summary:
* Share Dialogs are generally preferred because it will open the UI provided by Facebook (either a web browser or an app switch to the native Facebook app). Since Facebook owns the UI, it's the same as if the person was making a post themselves - they get a rich UI (can tag people or places, or change audiences). It's a one time post and doesn't need permissions
* The Share API is a programmatic call to the Graph API which requires an access token with authorized permissions. You might use it if you're building a custom UI for sharing, or expect to make many shares automatically.

**Comment by bendellarocco** [comment]
Thank you
