### ISSUE TITLE
login button always show "You have already authorized"

### ISSUE THREAD

**Issue by Fandekasp** [facebook/react-native-fbsdk#240]
This issue was previously reported in #99 , but got closed without giving a solution specific to the react-native-fbsdk package.
Since I only recently got started with react native and have no prior ios swift experience, I'm not sure how to resolve this issue.

I have SSO enabled in my facebook app, and when using iOS 9 in a simulator, I keep getting this message when trying to log in.

If I understand correctly, when login for the first time, the app opens a safari view, and the session gets shared. Then when trying to login again, since safari already has the session, that message is returned (although I don't understand the reasons for this behavior). 

Then why isn't the LoginButton onLogout logic fixed to log the user out from safari ? Shouldn't this become the new behavior for logout?
In the meantime, can you explain me how should I manually logout the user ?

Also, it looks like if a user already signed in facebook from Safari, the user should get auto-logged in my app without needing to click on login. Can you confirm this flow ? In which case, do you know how can I auto-login the user ?

Thank you for your support.

**Comment by chrisp-fb** [comment]
Hi,

There's two things going on that might help to explain this behavior better:
1/ Whether the person has granted permissions to the app before (i.e., such that it shows up on their FB account settings -> Apps)
2/ Whether the native app and FBSDK has an access token (which determines if the button says "Log In" or "Log Out").

People will see that "You've already authorized..." screen if they had previously granted permissions to the app (#1).  It is intentional because the SDK is not able to query either Safari or FB to know if the person has granted anything. Once the person clicks through that screen, a token will be returned back to the native/FBSDK. Assuming you have followed all the steps in the [Getting Started Guide](https://developers.facebook.com/docs/ios/getting-started/) including connecting the ApplicationDelegate, the SDK will cache the token so that the next app start will not open another login dialog (it sounds like you may be missing this step).

As you have noticed, "logging out" does not log out of their Facebook account, nor log out the Safari session - it just clears out the native app's token cache. It does not affect the state of #1.
