### ISSUE TITLE
I keep seeing the confirm page at every login click

### ISSUE THREAD

**Issue by steveleec** [facebook/react-native-fbsdk#28]
<img width="372" alt="screen shot 2015-09-07 at 5 26 52 pm" src="https://cloud.githubusercontent.com/assets/3300958/9724045/b6763e14-5585-11e5-8296-9dbe4f702ec7.png">

The user already granted permissions. However, every time the users logs out and logs in again, that screen is shown. Unless the app is asking for more permission or it is first time usage, the Confirm screen shouldn't appear.

Any suggestion to skip the Confirm screen after user grants access?
Thanks!

**Comment by mingflifb** [comment]
This is by design, any time there's an app switch this dialog will show, regardless of whether the user has authorized the app already.

**Comment by ceditoph** [comment]
@mingflifb There is no plan to change this?

**Comment by mingflifb** [comment]
This is by design to increase user trust, since flashes of app switch back and forth with no explanation is a bad experience. If the user has explicitly logged out of your app, and logs in again, they will see this dialog. If the user is not logged out explicitly, we will cache the access token so you can use it across app starts. Is your app logging out the user when it shuts down, or is the user explicitly choosing to log out?

**Comment by steveleec** [comment]
It makes sense now that you explained. Thanks for that. Just out of
curiosity, when you say "we will cache the access token", where exactly the
token is stored? In the server, cookies in browser? I know we can retrieve
user's token but from where we get it?

Thanks a lot for your quick response!

SM

**Comment by mingflifb** [comment]
It's securely stored locally on the device.

**Comment by kevinzzz007** [comment]
@steveleec I use ParseReact to do my login and it has a `ParseReact.currentUser` that saved the Facebook user, you might want to check that out

**Comment by kevinzzz007** [comment]
@mingflifb how do we access that access token?

**Comment by mingflifb** [comment]
Use the FBSDKAccessToken
