### ISSUE TITLE
'FBSDKCoreKit / FBSDKCoreKit.h' file not found

### ISSUE THREAD

**Issue by hasnainsakir99** [facebook/react-native-fbsdk#452]
I have created an empty project and setup a Facebook app and configured my plist file with the correct ID when I import the FBSDKCoreKit and FBSDKLoginKit and import the project in my bridging header I get an error saying ''FBSDKCoreKit / FBSDKCoreKit.h' file not foundt'. The error goes away once I take away these lines of code:

#import <FBSDKCoreKit/FBSDKCoreKit.h>

**Comment by liorbraginsky92** [comment]
I am also getting this issue even I installed FacebookSDK in `~/Documents/FacebookSDK` folder.
Anyone has any idea?

**Comment by Jithinag007** [comment]
this issues coming from latest xcode(10.x) facebook login working with xcode 9.x

**Comment by SvetoslavSlavov** [comment]
For XCode 10.x the Frameworks folder was missing for me. I created a folder Frameworks in ios folder and add inside Bolts.framework, FBSDKCoreKit.framework, FBSDKLoginKit.framework, FBSDKShareKit.framework. Then you have to link the libraries again. Go to Link Binary With Libraries remove them and add them again. The other possible issue can be if the Documents directory is in the iCloud. Then the files are not in your computer but they are stored in the cloud. You have to disable the cloud from Settings.

**Comment by mg4u** [comment]
> this issues coming from latest xcode(10.x) facebook login working with xcode 9.x

So what is the solution to make it works in Xcode 10?

**Comment by noahtallen** [comment]
The pods solution works in Xcode 10 👍

**Comment by elhachimi** [comment]
Hi @noahtallen, i don't think leaving   
```pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'```
line and doing `pod install` is a good idea because it installs `React` and other dependencies

**Comment by noahtallen** [comment]
@elhachimi, if you're already linking libraries through Pods which depend on react native, you'd probably already be installing react through pods too. At least in my case, all of my native 3rd party dependencies (including react native) go through pods

**Comment by elhachimi** [comment]
@noahtallen  i noticed that with only
```pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'```
in podfile does also install `FBSDKCoreKit`, `'FBSDKLoginKit'` ...

**Comment by noahtallen** [comment]
Hmm that's great! I'm not sure if I tested just adding the rn-fbsdk pod without the others, but it'd be great to hear if login still works without it!

**Comment by arunmenon1975** [comment]
What finally worked for me was:

- Instead of the official instructions here, i followed the instructions from the FB React Native SDK documentation to a T: [iOS Project Configuration](https://developers.facebook.com/docs/react-native/configure-ios). One of the steps requires adding a few dependencies [`npm install plist xcode adm-zip`] which i think can be safely removed/uninstalled after everything is done, though there is no explicit mention in the instructions
- Downloaded `FacebookSDK_Static.zip` from  [here](https://github.com/facebook/facebook-objc-sdk/releases), currently at `v5.2.3`.
- Copied the four frameworks from the downloaded SDK to the `Frameworks` directory in `Xcode`
- for the `Framework Search Paths`, besides `~/Documents/FacebookSDK`, added `$(HOME)/Documents/FacebookSDK`, `/Users//Documents/FacebookSDK`, `/Users/my_username/Documents/FacebookSDK`. I really don't think they are all required but i have it there from other suggestions.
- Clean build and then build

I tried all possible variations (with/without pods, different versions of sdks, drag drop linking, consuming React as a pod etc etc) but i was getting one error or the other.

I am on `react-native v0.59.10` with `react-native-fbsdk` at `0.10.1`

**Comment by IAmMarcellus** [comment]
I got this to work by using a variation of @noahtallen 's comment. I also removed the libs from xcode and used pods however I used
` pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
pod FacebookSDK`
instead of the pods that @noahtallen used for the facebook SDK as those are deprecated now.  However, to use this setup, react native must at version 0.60.0 or above, because the new SDK doesn't work with earlier versions.

**Comment by msqar** [comment]
@IAmMarcellus can you help me out please? I'm also using RN 0.60.4 with CocoaPods. Do i need to add the FacebookSDK under my ~/Documents and import the .framework files or that is no longer needed?
These are the versions that are installing on my pod install

```
Analyzing dependencies
Fetching podspec for `react-native-fbsdk` from `../node_modules/react-native-fbsdk`
Downloading dependencies
Installing Bolts (1.9.0)
Installing FBSDKCoreKit (5.3.0)
Installing FBSDKLoginKit (5.3.0)
Installing FBSDKMarketingKit (4.38.0)
Installing FBSDKPlacesKit (5.3.0)
Installing FBSDKShareKit (5.3.0)
Installing FacebookSDK (4.44.1)
Installing React (0.11.0)
Installing react-native-fbsdk (1.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 9 total pods installed.

[!] React has been deprecated
```

But I keep getting the 'FBSDKCoreKit/FBSDKCoreKit.h' file not found error.

Any ideas?

**Comment by felipeclopes** [comment]
I'm facing the same issue

**Comment by RahulLadybirdweb** [comment]
finally worked.
1. check out if you are using React Native Version >= 0.60 then you can use  react-native-fbsdk version >= 1.0.0 other wise you can use  react-native-fbsdk version <= 0.10.
2. run :- react-native link react-native-fbsdk
3. remove node-module and pods and podfile.lock.
4. run :- npm i
5. run :- cd ios pod install
6. run :- react-native run-android or react-native run-ios
