### ISSUE TITLE
FBSDKLoginManager.logOut(callback: func)

### ISSUE THREAD

**Issue by nlhkh** [facebook/react-native-fbsdk#48]
The way I setup my app, it will automatically transition to the main view instead of the login view when the app detects that I have already logged in. However, when I logout, and transition back to the login view, the logout process is not done yet, so the app thinks that it is still login, and transition me back to the main view. Since the `logOut` method is async, it should also accept a callback.

**Comment by dzhuowen** [comment]
The first issue (logout process is not done after transition back to login view) is now fixed by release0.0.6  The reason is native module is not promised to work on the main thread. 
The second second issue (logOut method callback) would be unnecessary then, because logOut method is sured to run on main thread.
