### ISSUE TITLE
readPermission set to get user_friends, but user always gets ask for permission for public profile only

### ISSUE THREAD

**Issue by kevinzzz007** [facebook/react-native-fbsdk#52]
Here is my code for the login button:
```
<FBSDKLoginButton
          onLoginFinished={(error, result) => {
            if (error) {
              alert('Error logging in.');
            } else {
              if (result.isCanceled) {
                alert('Login cancelled.');
              } else {
                FBSDKAccessToken.getCurrentAccessToken(
                    (token) => this.onFacebookLogin(token)
                  );
                }
                alert('Logged in.');
              }
            }
          }
          onLogoutFinished={() => alert('Logged out.')}
          readPermissions={['public_profile','email','user_friends']}
          publishPermissions={['publish_actions']}/>
```
but when I go to the Facebook page, the user is only asked to share public profile...

**Comment by kevinzzz007** [comment]
@philikon

**Comment by mingflifb** [comment]
Sorry about the confusing docs, we will update them going forward, but you cannot specify readPermissions and publishPermissions at the same time on the login button (because you need to separate the requests for read and write permissions), doing so will be equivalent to ONLY setting the publishPermissions, which means you're only requesting publish_actions. But when the user first logs in, they must grant public_profile before any publish permissions can be granted, so that's why you see only public profile.

In your case, you should set only the readPermissions, and then use the LoginManager to request the publish permissions at a later time (when the user does some action that actually requires a publish).

See login best practices: https://developers.facebook.com/docs/facebook-login/best-practices

And more docs on react native login: https://developers.facebook.com/docs/facebook-login/ios/react-native

**Comment by kevinzzz007** [comment]
@mingflifb thank you so much for such a fast reply!
