### ISSUE TITLE
React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by lsantamaria** [facebook/react-native-fbsdk#638]
I am receiving this error after installling the fbsdk to my RN project and running it on iOS. It seems that all the references or imports are referring to "React" instead of "React-Core", so the build fails because it does not find the modules.

If I am changing all the references from React/X to React-Core/React/X it works. More explanation in [this post](https://stackoverflow.com/questions/57871838/react-rctviewmanager-h-file-not-found-from-fbsdk-in-react-native-0-60).

So I had to rename all the .h files to get it working temporarily. Any cleaner idea to get it working?

**Comment by rewieer** [comment]
Had the same problem this morning. 
As of myself the problem was a configuration problem. I just moved from 0.59.0 to 0.61.0-rc.3 and installed React-Native and its dependencies through Cocoapods.
Unfortunately this is a one-year old project and it used to include binaries directly into `Build Phases -> Link Binary With Libraries.`.

I solved the problem by removing everything in here and adding libPods-myProject.a (the binary file generated by cocoapods).

I copied the Podfile file directly from [https://react-native-community.github.io/upgrade-helper/](https://react-native-community.github.io/upgrade-helper/) and now it works perfectly fine.

**Comment by lsantamaria** [comment]
Hi @rewieer, 
I tried what you say and then I got this error:

```
 *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: null is not an object (evaluating 'n.logInWithPermissions')', reason: 'Unhandled JS Exception: null is not an object (evaluating 'n.logInWithPermissions'), stack:
logInWithPermissions@1002:137
```
So that I decided to add there(Build Phases)  libRCTFBSDK.a, and then is when the problem with React and React-Core naming arises. 

Do you know how can I get this working?

**Comment by lsantamaria** [comment]
I solved it finally without adding  libRCTFBSDK.a.

The problem was on the Podfile, the last section was removing React from the Targets, and I have needed to add this lines:

```
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_native_modules!
```
So, in conclusion, the problem was that after upgrading to 0.60, the Podfile was not correctly upgraded so React module was not added to the iOS target.
