### ISSUE TITLE
How to get the userName via GraphRequestManager?

### ISSUE THREAD

**Issue by alvaro1728** [facebook/react-native-fbsdk#665]
### My dependencies:

    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-fbsdk": "^1.0.4",

### My question:
When I'm on my FB page and I click on a user's name link, I get sent to https://facebook.com/userName and I see that user's profile. So now that I'm using the GraphRequestManager API to get the user's information, I'd like to get the "userName".  I get an "id" and the "name", but I don't know how to get the "userName" that would allow me to navigate to the user's profile page.

Thanks!
Alvaro

**Comment by gmertk** [comment]
Hi @alvaro1728, this isn't really about the react-native-fbsdk as it isn't possible with the underlying Graph API:
- username field isn't available since Graph API v2.0.
- app scoped id redirects were disabled a year ago. More info https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/
So Graph API doesn't provide profile links anymore.
