### ISSUE TITLE
Sharing is broken in sample app: "fbcdn.net urls are not allowed"

### ISSUE THREAD

**Issue by navels** [facebook/react-native-fbsdk#73]
I have the sample project up and running with login working.  The app successfully pulls the photos from the New Horizons Pluto facebook page.  However, when I click "Share" I get this error in the SFSafariViewController:

    An error occurred. Please try again later.
    API Error Code: 1500
    API Error Description: The url you supplied is invalid
    Error Message: fbcdn.net urls are not allowed

If I hard-code an imgur link in Feed._sharePhoto(), I get the expected sharing dialog.

Wondering if this is an issue with the 4.6+ SDK using SFSafariViewController instead of the native app . . .

**Comment by dzhuowen** [comment]
Thanks for reporting the issue! It looks to me more like a server side issue, will look into this.

**Comment by phwd** [comment]
In here https://github.com/facebook/react-native-fbsdk/blob/master/Sample/Feed.js#L98

Shouldn't the first param be the link and not the picture source?

Of course this means refactoring so that https://github.com/facebook/react-native-fbsdk/blob/master/Sample/Feed.js#L57

includes the link field. 

And if the code change is going to happen, maybe even include the id field as well so that the key issue can dealt with?

http://imgur.com/Z4vQ4KK

**Comment by navels** [comment]
I agree that the first field should be the link (contentURL according to the docs).  That doesn't fix the problem.

By the way, I am getting the "fbcdn.net urls are not allowed" when authenticating with my own fb application.  When I use the one that comes with the sample app (New Horizons) and I log in and get the feed just fine but sharing results in this:

    An error occurred. Please try again later.

**Comment by phwd** [comment]
It doesn't directly fix the problem, but that's the cause of it.
http://stackoverflow.com/a/9335869/321505

> We no longer allow stream stories to contain images that are hosted on the fbcdn.net domain. The images associated with these URLs aren't always optimized for stream stories and occasionally resulted in errors, leading to a poor user experience. Make sure your stream attachments don't reference images with this domain. You should host the images locally

A quick fix to get to a share would be something along the lines of

`var linkContent = new FBSDKShareLinkContent('https://facebook.com/716071995190001', 'A picture from New Horizons.', 'New Horizons    ');`

And let Facebook handle grabbing the correct image and description since the image is already an object on Facebook.

Compared to 

`var linkContent = new FBSDKShareLinkContent('http://phwd.tumblr.com/post/134191293215', 'A picture from New Horizons.', 'New Horizons', 'http://40.media.tumblr.com/526c9c74e2a8a1ec4a8f4d8d9afa8a29/tumblr_nng69nDOew1r7edw3o1_1280.jpg');`

http://imgur.com/04MmV8H

**Comment by navels** [comment]
Thanks, that worked.

**Comment by dzhuowen** [comment]
I cannot find the excerpt in http://stackoverflow.com/a/9335869/321505 from developers.facebook.com, but we have consistently told developers we don't support fbcdn url. 
The Sample App does have problem here.
