### ISSUE TITLE
Please update peer dependencies to support React Native 0.9.0

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native-fbsdk#9]
Hello,

I've just created new app from scratch using React Native 0.9.0
when trying to install ```react-native-fbsdklogin``` i get the following error:
```
npm WARN peerDependencies The peer dependency react-native@^0.8.0 included from react-native-fbsdklogin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/ranyefet/.nvm/versions/io.js/v2.5.0/bin/iojs" "/Users/ranyefet/.nvm/versions/io.js/v2.5.0/bin/npm" "install" "--save" "react-native-fbsdklogin"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.9.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-fbsdklogin@0.0.3 wants react-native@^0.8.0
```

Can you please upgrade the package to use 0.9.0?

Thanks,
Ran.

**Comment by paulwittmann** [comment]
+1

**Comment by shohey1226** [comment]
This happens on 0.10.0-rc too.

**Comment by cphackm** [comment]
@philikon Could you get this in order for the next release?

**Comment by philikon** [comment]
Yeah, definitely. I don't think pinning down the React Native version is a sustainable way forward anyway.

**Comment by danscan** [comment]
+1– trying to use this with `0.10.0-rc` now.

**Comment by pickhardt** [comment]
Anyone have a good way around this without having to wait? e.g. a way to locally say "ignore the peer dependencies for this"

**Comment by cphackm** [comment]
@pickhardt You could always change the version on the peer dependency in the package.json files.  For example:

```js
...
"peerDependencies": {
    "react-native": ">=0.8.0"
  },
...
```

Will accept any version of React Native from 0.8.0 up.

**Comment by philikon** [comment]
Yeah, what @cphackm says. Just hack it locally in your `node_modules/.../package.json` files. I'll have 0.0.4 out hopefully tomorrow.

**Comment by justinmakaila** [comment]
@cphackm @philikon 

I'm still getting the error, even with the suggested workaround:

package.json
```
...
  "peerDependencies": {
    "react-native": ">=0.8.0"
  },
...
```

Error:
```
j ~> npm install
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/iojs/2.4.0/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.4.0
npm ERR! npm  v2.12.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-fbsdkcore@0.0.3 wants react-native@>=0.8.0
npm ERR! peerinvalid Peer react-native-fbsdklogin@0.0.3 wants react-native@>=0.8.0

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/npm-debug.log
```

**Comment by philikon** [comment]
I just released 0.0.4. Please try that and reopen if you still have any problems. Thanks!

**Comment by justinmakaila** [comment]
Getting the same exact error message, the difference being the version of `fbsdkcore` and `fbsdklogin` is `0.0.4`

**Comment by justinmakaila** [comment]
That's to install 0.10.0

**Comment by philikon** [comment]
Hrm, I see. npm does not like the `-rc` suffix...

**Comment by paulwittmann** [comment]
As far as I can remember these were the steps to get my current project working with 0.9.0. Note that you may have other `react-native-...` packages still depending on 0.8. I have to fix `react-native-fbsdklogin`, `react-native-fbsdkcore` and `react-native-slider` in my repo.

1. `npm install` (with 0.8 in my project's `package.json`)
2. adjust `react-native` versions in `package.json`s of all relevant packages in `node_modules` (like @cphackm [suggested](https://github.com/facebook/react-native-fbsdk/issues/9#issuecomment-133235582))
3. `npm uninstall react-native`
4. `npm install react-native@0.9.0`
5. `npm install`

I had some issues with packages not getting properly installed (`lodash`, e.g., was missing one of its folders), so I had to remove and reinstall those, but I think this was due to running `npm install` before I had fixed all relevant dependencies in `node_modules`.

Hope this helps. Let's cross our fingers package maintainers soon upgrade to 0.9.0!
